// RootLayout.tsx
import "./globals.css";
import { ReactNode } from 'react'; 
import { Metadata } from "next";
import AppQueryClientProvider from "@/context/QueryClientProvider";

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Careerseal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-white">
        <AppQueryClientProvider>
          <main className="min-h-screen">{children}</main>
        </AppQueryClientProvider>
      </body>
    </html>
  );
}
